# Generated by Django 4.2.19 on 2025-06-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('technology', 'Technology'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
